// アイテムの基本情報（1個に対して一意に定まる情報のみ）。
// 攻撃力・効果・入手方法・価格などのゲーム的なパラメータはまだ未定。
// 決まり次第、lib/characters.ts / lib/battle-stages.ts と同様に別ファイルで管理する。
//
// 元データ: サンプル画像フォルダとは別の
// C:\Users\田中宏樹\Documents\Codex\hirogames_images\assets\items\catalog_v1
// からコピーしたもの（詳細は docs/spec/items.md 参照）。

export type ItemType = "片手剣" | "法器" | "弓" | "アーティファクト";
export type ItemRarity = "C" | "B" | "A" | "S" | "SS";
export type ArtifactSlot = "護符" | "指輪" | "腕輪" | "首飾り" | "耳飾り" | "ブローチ" | "帯留め";

export interface ItemBaseInfo {
  id: string;
  name: string;
  description: string;
  type: ItemType;
  // アーティファクトのみ持つ、装備部位の種類
  slot?: ArtifactSlot;
  rarity: ItemRarity;
  asset: string;
}

export const ITEM_BASE_INFO: ItemBaseInfo[] = [
  {
    id: "i001",
    name: "木刀",
    description: "丈夫な木を削って作った剣。\n切れ味は悪いが、叩かれるととても痛い。",
    type: "片手剣",
    rarity: "C",
    asset: "/items/i001.png",
  },
  {
    id: "i002",
    name: "石の剣",
    description: "磨き上げた石で作った片手剣。\n研ぐより先に、持ち上げる練習が必要だ。",
    type: "片手剣",
    rarity: "C",
    asset: "/items/i002.png",
  },
  {
    id: "i003",
    name: "銅剣",
    description: "赤褐色の銅で作った片手剣。\n新品の輝きは、手入れをする人だけの特権。",
    type: "片手剣",
    rarity: "C",
    asset: "/items/i003.png",
  },
  {
    id: "i004",
    name: "ブロンズエッジ",
    description: "銅と錫を合わせた青銅で作った片手剣。\n古そうに見えるが、昨日できたばかりだ。",
    type: "片手剣",
    rarity: "C",
    asset: "/items/i004.png",
  },
  {
    id: "i005",
    name: "鉄剣",
    description: "堅実な鉄で作った片手剣。\n頼りになるが、雨の日には少し気を遣う。",
    type: "片手剣",
    rarity: "C",
    asset: "/items/i005.png",
  },
  {
    id: "i006",
    name: "鋼打ち・正宗",
    description: "よく鍛えた鋼で作った片手剣。\n丈夫さが自慢。持ち主の腰まで丈夫にはしない。",
    type: "片手剣",
    rarity: "B",
    asset: "/items/i006.png",
  },
  {
    id: "i007",
    name: "シルバーファング",
    description: "銀を主体とする合金で作った片手剣。\n鏡代わりにするなら、刃先には近づかないこと。",
    type: "片手剣",
    rarity: "B",
    asset: "/items/i007.png",
  },
  {
    id: "i008",
    name: "黒曜・烏羽",
    description: "黒く艶やかな黒曜石で作った片手剣。\n黒い刃は格好いい。指紋もよく目立つ。",
    type: "片手剣",
    rarity: "B",
    asset: "/items/i008.png",
  },
  {
    id: "i009",
    name: "琥珀の剣",
    description: "魔力で硬化させた琥珀で作った片手剣。\nおいしそうな色でも、かじってはいけない。",
    type: "片手剣",
    rarity: "B",
    asset: "/items/i009.png",
  },
  {
    id: "i010",
    name: "金の剣",
    description: "金と他の金属を混ぜて作った剣。\n武器としても強いが、金は資産にもなる。",
    type: "片手剣",
    rarity: "B",
    asset: "/items/i010.png",
  },
  {
    id: "i011",
    name: "ミスリルセイバー",
    description: "軽く青銀色に輝くミスリルで作った片手剣。\n剣は軽いが、買う決断は重かった。",
    type: "片手剣",
    rarity: "A",
    asset: "/items/i011.png",
  },
  {
    id: "i012",
    name: "翠晶・若葉",
    description: "緑の光を宿す翠晶で作った片手剣。\n草に紛れるので、昼寝の前に場所を覚えよう。",
    type: "片手剣",
    rarity: "A",
    asset: "/items/i012.png",
  },
  {
    id: "i013",
    name: "紅晶の剣",
    description: "深紅に輝く紅晶で作った片手剣。\n熱そうに見えるが、夕食は温められない。",
    type: "片手剣",
    rarity: "A",
    asset: "/items/i013.png",
  },
  {
    id: "i014",
    name: "月銀・朧",
    description: "月光を帯びる月銀で作った片手剣。\n夜道には心強いが、寝室では鞘にしまおう。",
    type: "片手剣",
    rarity: "A",
    asset: "/items/i014.png",
  },
  {
    id: "i015",
    name: "蒼玉の剣",
    description: "魔力を通す蒼玉で作った片手剣。\n透き通る刃に、持ち主の懐事情は映らない。",
    type: "片手剣",
    rarity: "A",
    asset: "/items/i015.png",
  },
  {
    id: "i016",
    name: "星鉄・流星",
    description: "隕石から採れた星鉄で作った片手剣。\n空から来たが、振ればちゃんと筋肉痛になる。",
    type: "片手剣",
    rarity: "S",
    asset: "/items/i016.png",
  },
  {
    id: "i017",
    name: "竜鱗鋼の牙",
    description: "竜鱗を練り込んだ竜鱗鋼で作った片手剣。\n持ち主より、材料のほうが武勇伝を持っている。",
    type: "片手剣",
    rarity: "S",
    asset: "/items/i017.png",
  },
  {
    id: "i018",
    name: "精霊銀の剣",
    description: "精霊の加護を宿す精霊銀で作った片手剣。\n精霊にも、たまには鞘で休む時間をあげよう。",
    type: "片手剣",
    rarity: "S",
    asset: "/items/i018.png",
  },
  {
    id: "i019",
    name: "黎明晶・東雲",
    description: "朝焼けを閉じ込めた黎明晶で作った片手剣。\nいつでも朝の気分。早起きできるかは本人次第。",
    type: "片手剣",
    rarity: "S",
    asset: "/items/i019.png",
  },
  {
    id: "i020",
    name: "永霜晶の剣",
    description: "溶けない氷の結晶である永霜晶で作った片手剣。\nひんやりしているが、食料保存は専門外。",
    type: "片手剣",
    rarity: "S",
    asset: "/items/i020.png",
  },
  {
    id: "i021",
    name: "創世剣アケボノ",
    description: "夜明けを封じた白金の刃と、日輪の鍔を持つ神剣。\n伝説の持ち主も、最初は使い方を聞いたはずだ。",
    type: "片手剣",
    rarity: "SS",
    asset: "/items/i021.png",
  },
  {
    id: "i022",
    name: "天樹ノ太刀",
    description: "世界樹の芯から生まれ、翠の葉脈が輝く聖なる剣。\n神話に登場するが、持ち運びは今の持ち主の仕事。",
    type: "片手剣",
    rarity: "SS",
    asset: "/items/i022.png",
  },
  {
    id: "i023",
    name: "STAR BREAKER",
    description: "星の核を鍛えた群青の刀身に、金の星図が巡る剣。\n宝物庫より、たまには外の空気が好きらしい。",
    type: "片手剣",
    rarity: "SS",
    asset: "/items/i023.png",
  },
  {
    id: "i024",
    name: "フロストエターナル",
    description: "決して溶けない氷の刃に、雪華の鍔を備える神剣。\n名前を名乗るだけで、自己紹介が少し長くなる。",
    type: "片手剣",
    rarity: "SS",
    asset: "/items/i024.png",
  },
  {
    id: "i025",
    name: "竜祖の牙",
    description: "最初の竜が遺した紅金の牙を刃にした伝説の剣。\n世界を救った後も、手入れだけは省けない。",
    type: "片手剣",
    rarity: "SS",
    asset: "/items/i025.png",
  },
  {
    id: "i026",
    name: "桜木の法杖",
    description: "桜の木を削り、術式を刻んだ法杖。\n花は咲かないが、術者の才能は咲くかもしれない。",
    type: "法器",
    rarity: "C",
    asset: "/items/i026.png",
  },
  {
    id: "i027",
    name: "石の呪符板",
    description: "磨き上げた石を主材に使った魔法用の法器。\n教科書より重いが、覚える文字は少なくて済む。",
    type: "法器",
    rarity: "C",
    asset: "/items/i027.png",
  },
  {
    id: "i028",
    name: "銅の術鈴",
    description: "赤褐色の銅を主材に使った魔法用の法器。\nいい音が鳴る。いい魔法が出るかは別の話。",
    type: "法器",
    rarity: "C",
    asset: "/items/i028.png",
  },
  {
    id: "i029",
    name: "青銅の術鏡",
    description: "銅と錫を合わせた青銅を主材に使った魔法用の法器。\n映る寝癖は、魔法の乱れではない。",
    type: "法器",
    rarity: "C",
    asset: "/items/i029.png",
  },
  {
    id: "i030",
    name: "鉄の魔導球",
    description: "堅実な鉄を主材に使った魔法用の法器。\n転がすと床がへこむ。占いには向いていない。",
    type: "法器",
    rarity: "C",
    asset: "/items/i030.png",
  },
  {
    id: "i031",
    name: "鋼装の魔導書",
    description: "よく鍛えた鋼を主材に使った魔法用の法器。\n中身は難しいが、表紙はもっと硬い。",
    type: "法器",
    rarity: "B",
    asset: "/items/i031.png",
  },
  {
    id: "i032",
    name: "銀の三日月鏡",
    description: "銀を主体とする合金を主材に使った魔法用の法器。\n月を見る道具だが、つい自分の顔も見てしまう。",
    type: "法器",
    rarity: "B",
    asset: "/items/i032.png",
  },
  {
    id: "i033",
    name: "黒曜石の法珠",
    description: "黒く艶やかな黒曜石を主材に使った魔法用の法器。\n未来より先に、磨き残しが見えてしまう。",
    type: "法器",
    rarity: "B",
    asset: "/items/i033.png",
  },
  {
    id: "i034",
    name: "琥珀の振り子",
    description: "魔力で硬化させた琥珀を主材に使った魔法用の法器。\nよく揺れる。迷っているのが石か術者かは不明。",
    type: "法器",
    rarity: "B",
    asset: "/items/i034.png",
  },
  {
    id: "i035",
    name: "黄金の輝く法器",
    description: "金と他の金属を混ぜた合金を主材に使った魔法用の法器。\n魔力が切れても、値打ちまでは消えない。",
    type: "法器",
    rarity: "B",
    asset: "/items/i035.png",
  },
  {
    id: "i036",
    name: "ミスリルの星盤",
    description: "軽く青銀色に輝くミスリルを主材に使った魔法用の法器。\n星を読む前に、説明書を読む勇気がいる。",
    type: "法器",
    rarity: "A",
    asset: "/items/i036.png",
  },
  {
    id: "i037",
    name: "翠晶の浮遊環",
    description: "緑の光を宿す翠晶を主材に使った魔法用の法器。\n浮いているので、机を片付けた気分になれる。",
    type: "法器",
    rarity: "A",
    asset: "/items/i037.png",
  },
  {
    id: "i038",
    name: "紅晶の王笏",
    description: "深紅に輝く紅晶を主材に使った魔法用の法器。\n持つだけで偉そうに見える。背筋も伸ばそう。",
    type: "法器",
    rarity: "A",
    asset: "/items/i038.png",
  },
  {
    id: "i039",
    name: "月銀の魔灯",
    description: "月光を帯びる月銀を主材に使った魔法用の法器。\n夜更かしの言い訳が、また一つ増えてしまった。",
    type: "法器",
    rarity: "A",
    asset: "/items/i039.png",
  },
  {
    id: "i040",
    name: "蒼玉の法珠",
    description: "魔力を通す蒼玉を主材に使った魔法用の法器。\n丸く磨かれているが、扱いまで丸投げはできない。",
    type: "法器",
    rarity: "A",
    asset: "/items/i040.png",
  },
  {
    id: "i041",
    name: "星鉄の天球儀",
    description: "隕石から採れた星鉄を主材に使った魔法用の法器。\n世界は回る。これも回る。目まで回さないように。",
    type: "法器",
    rarity: "S",
    asset: "/items/i041.png",
  },
  {
    id: "i042",
    name: "竜鱗鋼の魔導書",
    description: "竜鱗を練り込んだ竜鱗鋼を主材に使った魔法用の法器。\n表紙は頑丈だが、宿題を代わりには解かない。",
    type: "法器",
    rarity: "S",
    asset: "/items/i042.png",
  },
  {
    id: "i043",
    name: "精霊銀の花杖",
    description: "精霊の加護を宿す精霊銀を主材に使った魔法用の法器。\n水やりは不要。話しかけるのは止められていない。",
    type: "法器",
    rarity: "S",
    asset: "/items/i043.png",
  },
  {
    id: "i044",
    name: "黎明晶の法冠",
    description: "朝焼けを閉じ込めた黎明晶を主材に使った魔法用の法器。\n頭上は明るいが、難問の答えまでは照らさない。",
    type: "法器",
    rarity: "S",
    asset: "/items/i044.png",
  },
  {
    id: "i045",
    name: "永霜晶の雪輪",
    description: "溶けない氷の結晶である永霜晶を主材に使った魔法用の法器。\n夏には人気者。冬には少し距離を置かれる。",
    type: "法器",
    rarity: "S",
    asset: "/items/i045.png",
  },
  {
    id: "i046",
    name: "はじまりの書",
    description: "白金の表紙に、世界の誕生を示す輪が重なる神書。\n伝説の持ち主も、最初は使い方を聞いたはずだ。",
    type: "法器",
    rarity: "SS",
    asset: "/items/i046.png",
  },
  {
    id: "i047",
    name: "コズミックオーブ",
    description: "小さな星空を内側に閉じ込めた、群青の球形法器。\n神話に登場するが、持ち運びは今の持ち主の仕事。",
    type: "法器",
    rarity: "SS",
    asset: "/items/i047.png",
  },
  {
    id: "i048",
    name: "時ノ理",
    description: "金銀の歯車と透明な環が重なる、時を司る神の盤。\n宝物庫より、たまには外の空気が好きらしい。",
    type: "法器",
    rarity: "SS",
    asset: "/items/i048.png",
  },
  {
    id: "i049",
    name: "天樹杖ハナムスビ",
    description: "世界樹の枝先に四季の花を結んだ伝説の短杖。\n名前を名乗るだけで、自己紹介が少し長くなる。",
    type: "法器",
    rarity: "SS",
    asset: "/items/i049.png",
  },
  {
    id: "i050",
    name: "FIRST LIGHT",
    description: "白い炎を水晶の殻に収めた、最初の星の魔灯。\n世界を救った後も、手入れだけは省けない。",
    type: "法器",
    rarity: "SS",
    asset: "/items/i050.png",
  },
  {
    id: "i051",
    name: "白樺の弓",
    description: "白樺の木をしならせて作った弓。\n森では目立たない。置き忘れると自分も困る。",
    type: "弓",
    rarity: "C",
    asset: "/items/i051.png",
  },
  {
    id: "i052",
    name: "石芯の弓",
    description: "磨いた石を弓身の芯に組み込み、木で支えた弓。\n矢は軽い。荷物まで軽いとは言っていない。",
    type: "弓",
    rarity: "C",
    asset: "/items/i052.png",
  },
  {
    id: "i053",
    name: "カッパーボウ",
    description: "銅を主材に使った赤褐色の弓。赤銅はここでは色の呼称。\n夕日に光る姿だけなら、名射手にも見える。",
    type: "弓",
    rarity: "C",
    asset: "/items/i053.png",
  },
  {
    id: "i054",
    name: "ブロンズアーチ",
    description: "銅と錫を合わせた青銅を弓身の主材に使った弓。\n骨董品と間違われるので、値札は外しておこう。",
    type: "弓",
    rarity: "C",
    asset: "/items/i054.png",
  },
  {
    id: "i055",
    name: "アイアンストリング",
    description: "堅実な鉄を弓身の主材に使った弓。\n腕前の前に、腕の力を試してくる。",
    type: "弓",
    rarity: "C",
    asset: "/items/i055.png",
  },
  {
    id: "i056",
    name: "スチールボウ",
    description: "よく鍛えた鋼を弓身の主材に使った弓。\n弦を張る時間だけは、気を抜いてはいけない。",
    type: "弓",
    rarity: "B",
    asset: "/items/i056.png",
  },
  {
    id: "i057",
    name: "シルバーウィング",
    description: "銀を主体とする合金を弓身の主材に使った弓。\n月夜に映える。隠れたい夜には少し困る。",
    type: "弓",
    rarity: "B",
    asset: "/items/i057.png",
  },
  {
    id: "i058",
    name: "黒曜石の複合弓",
    description: "黒く艶やかな黒曜石を弓身の主材に使った弓。\n静かな見た目だが、手入れには注文が多い。",
    type: "弓",
    rarity: "B",
    asset: "/items/i058.png",
  },
  {
    id: "i059",
    name: "琥珀のハニーボウ",
    description: "魔力で硬化させた琥珀を弓身の主材に使った弓。\n蜂蜜のように見えるが、熊への贈り物には不向き。",
    type: "弓",
    rarity: "B",
    asset: "/items/i059.png",
  },
  {
    id: "i060",
    name: "ゴールドボウ",
    description: "金と他の金属を混ぜた合金を弓身の主材に使った弓。\n矢より先に、商人の視線を集めてしまう。",
    type: "弓",
    rarity: "B",
    asset: "/items/i060.png",
  },
  {
    id: "i061",
    name: "ミスリルアーチ",
    description: "軽く青銀色に輝くミスリルを弓身の主材に使った弓。\n軽さに驚き、値段でもう一度驚く。",
    type: "弓",
    rarity: "A",
    asset: "/items/i061.png",
  },
  {
    id: "i062",
    name: "翡翠色の翠晶弓",
    description: "緑の光を宿す翠晶を弓身の主材に使った弓。\n森によくなじむが、木に返してはいけない。",
    type: "弓",
    rarity: "A",
    asset: "/items/i062.png",
  },
  {
    id: "i063",
    name: "紅晶のスカーレット",
    description: "深紅に輝く紅晶を弓身の主材に使った弓。\n赤いからといって、狙いまで熱くならないように。",
    type: "弓",
    rarity: "A",
    asset: "/items/i063.png",
  },
  {
    id: "i064",
    name: "月銀の弓",
    description: "月光を帯びる月銀を弓身の主材に使った弓。\n月は狙えても、届くかどうかは別の問題。",
    type: "弓",
    rarity: "A",
    asset: "/items/i064.png",
  },
  {
    id: "i065",
    name: "サファイアアーチ",
    description: "魔力を通す蒼玉を弓身の主材に使った弓。\n澄んだ青さに見とれると、的を見失う。",
    type: "弓",
    rarity: "A",
    asset: "/items/i065.png",
  },
  {
    id: "i066",
    name: "星鉄のスカイライン",
    description: "隕石から採れた星鉄を弓身の主材に使った弓。\n星には届かないが、気分だけは届きそうだ。",
    type: "弓",
    rarity: "S",
    asset: "/items/i066.png",
  },
  {
    id: "i067",
    name: "竜鱗鋼の弓",
    description: "竜鱗を練り込んだ竜鱗鋼を弓身の主材に使った弓。\n竜相手に使うと、少し気まずいかもしれない。",
    type: "弓",
    rarity: "S",
    asset: "/items/i067.png",
  },
  {
    id: "i068",
    name: "精霊銀の息吹",
    description: "精霊の加護を宿す精霊銀を弓身の主材に使った弓。\n森の声は聞こえるが、的の位置までは教えない。",
    type: "弓",
    rarity: "S",
    asset: "/items/i068.png",
  },
  {
    id: "i069",
    name: "暁色の黎明晶弓",
    description: "朝焼けを閉じ込めた黎明晶を弓身の主材に使った弓。\n夕方でも朝焼け色。待ち合わせの時計には使えない。",
    type: "弓",
    rarity: "S",
    asset: "/items/i069.png",
  },
  {
    id: "i070",
    name: "永霜晶の凍月",
    description: "溶けない氷の結晶である永霜晶を弓身の主材に使った弓。\n冷静に狙える。手袋の用意も忘れずに。",
    type: "弓",
    rarity: "S",
    asset: "/items/i070.png",
  },
  {
    id: "i071",
    name: "天樹弓コダマ",
    description: "世界樹の若枝が弓の形に育った、緑光の神弓。\n伝説の持ち主も、最初は使い方を聞いたはずだ。",
    type: "弓",
    rarity: "SS",
    asset: "/items/i071.png",
  },
  {
    id: "i072",
    name: "STAR CHASER",
    description: "両端を星の輪が飾る、夜空色の伝説の弓。\n神話に登場するが、持ち運びは今の持ち主の仕事。",
    type: "弓",
    rarity: "SS",
    asset: "/items/i072.png",
  },
  {
    id: "i073",
    name: "日輪穿ち",
    description: "太陽の円弧を象った金の弓身と光の弦を持つ神弓。\n宝物庫より、たまには外の空気が好きらしい。",
    type: "弓",
    rarity: "SS",
    asset: "/items/i073.png",
  },
  {
    id: "i074",
    name: "ムーンセレナーデ",
    description: "月光の結晶で形作られた、白く透き通る神弓。\n名前を名乗るだけで、自己紹介が少し長くなる。",
    type: "弓",
    rarity: "SS",
    asset: "/items/i074.png",
  },
  {
    id: "i075",
    name: "ぜったい当てたい号",
    description: "最初の風竜の角を弓身にした、翼飾りの神弓。\n名前には切実な願いがこもる。必中とは書いていない。",
    type: "弓",
    rarity: "SS",
    asset: "/items/i075.png",
  },
  {
    id: "i076",
    name: "楠木の護符",
    description: "丈夫な木を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "C",
    asset: "/items/i076.png",
  },
  {
    id: "i077",
    name: "石の護符",
    description: "磨き上げた石を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "C",
    asset: "/items/i077.png",
  },
  {
    id: "i078",
    name: "銅の護符",
    description: "赤褐色の銅を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "C",
    asset: "/items/i078.png",
  },
  {
    id: "i079",
    name: "青銅の護符",
    description: "銅と錫を合わせた青銅を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "C",
    asset: "/items/i079.png",
  },
  {
    id: "i080",
    name: "鉄の護符",
    description: "堅実な鉄を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "C",
    asset: "/items/i080.png",
  },
  {
    id: "i081",
    name: "鋼の護符",
    description: "よく鍛えた鋼を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "B",
    asset: "/items/i081.png",
  },
  {
    id: "i082",
    name: "銀の護符",
    description: "銀を主体とする合金を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "B",
    asset: "/items/i082.png",
  },
  {
    id: "i083",
    name: "黒曜石の護符",
    description: "黒く艶やかな黒曜石を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "B",
    asset: "/items/i083.png",
  },
  {
    id: "i084",
    name: "琥珀の護符",
    description: "魔力で硬化させた琥珀を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "B",
    asset: "/items/i084.png",
  },
  {
    id: "i085",
    name: "金の護符",
    description: "金と他の金属を混ぜた合金を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "B",
    asset: "/items/i085.png",
  },
  {
    id: "i086",
    name: "ミスリルの護符",
    description: "軽く青銀色に輝くミスリルを主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "A",
    asset: "/items/i086.png",
  },
  {
    id: "i087",
    name: "翠晶の護符",
    description: "緑の光を宿す翠晶を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "A",
    asset: "/items/i087.png",
  },
  {
    id: "i088",
    name: "紅晶の護符",
    description: "深紅に輝く紅晶を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "A",
    asset: "/items/i088.png",
  },
  {
    id: "i089",
    name: "月銀の護符",
    description: "月光を帯びる月銀を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "A",
    asset: "/items/i089.png",
  },
  {
    id: "i090",
    name: "蒼玉の護符",
    description: "魔力を通す蒼玉を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "A",
    asset: "/items/i090.png",
  },
  {
    id: "i091",
    name: "星鉄の護符",
    description: "隕石から採れた星鉄を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "S",
    asset: "/items/i091.png",
  },
  {
    id: "i092",
    name: "竜鱗鋼の護符",
    description: "竜鱗を練り込んだ竜鱗鋼を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "S",
    asset: "/items/i092.png",
  },
  {
    id: "i093",
    name: "精霊銀の護符",
    description: "精霊の加護を宿す精霊銀を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "S",
    asset: "/items/i093.png",
  },
  {
    id: "i094",
    name: "黎明晶の護符",
    description: "朝焼けを閉じ込めた黎明晶を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "S",
    asset: "/items/i094.png",
  },
  {
    id: "i095",
    name: "永霜晶の護符",
    description: "溶けない氷の結晶である永霜晶を主材に仕立てた護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "S",
    asset: "/items/i095.png",
  },
  {
    id: "i096",
    name: "創世金の護符",
    description: "神話の素材「創世金」を核にした護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "SS",
    asset: "/items/i096.png",
  },
  {
    id: "i097",
    name: "天樹の芯の護符",
    description: "神話の素材「天樹の芯」を核にした護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "SS",
    asset: "/items/i097.png",
  },
  {
    id: "i098",
    name: "時晶の護符",
    description: "神話の素材「時晶」を核にした護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "SS",
    asset: "/items/i098.png",
  },
  {
    id: "i099",
    name: "星母の涙石の護符",
    description: "神話の素材「星母の涙石」を核にした護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "SS",
    asset: "/items/i099.png",
  },
  {
    id: "i100",
    name: "不死鳥の羽の護符",
    description: "神話の素材「不死鳥の羽」を核にした護符。\nいつもより長く戦えそう",
    type: "アーティファクト",
    slot: "護符",
    rarity: "SS",
    asset: "/items/i100.png",
  },
  {
    id: "i101",
    name: "黒檀の指輪",
    description: "丈夫な木を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "C",
    asset: "/items/i101.png",
  },
  {
    id: "i102",
    name: "石の指輪",
    description: "磨き上げた石を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "C",
    asset: "/items/i102.png",
  },
  {
    id: "i103",
    name: "銅の指輪",
    description: "赤褐色の銅を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "C",
    asset: "/items/i103.png",
  },
  {
    id: "i104",
    name: "青銅の指輪",
    description: "銅と錫を合わせた青銅を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "C",
    asset: "/items/i104.png",
  },
  {
    id: "i105",
    name: "鉄の指輪",
    description: "堅実な鉄を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "C",
    asset: "/items/i105.png",
  },
  {
    id: "i106",
    name: "鋼の指輪",
    description: "よく鍛えた鋼を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "B",
    asset: "/items/i106.png",
  },
  {
    id: "i107",
    name: "銀の指輪",
    description: "銀を主体とする合金を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "B",
    asset: "/items/i107.png",
  },
  {
    id: "i108",
    name: "黒曜石の指輪",
    description: "黒く艶やかな黒曜石を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "B",
    asset: "/items/i108.png",
  },
  {
    id: "i109",
    name: "琥珀の指輪",
    description: "魔力で硬化させた琥珀を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "B",
    asset: "/items/i109.png",
  },
  {
    id: "i110",
    name: "金の指輪",
    description: "金と他の金属を混ぜた合金を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "B",
    asset: "/items/i110.png",
  },
  {
    id: "i111",
    name: "ミスリルの指輪",
    description: "軽く青銀色に輝くミスリルを主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "A",
    asset: "/items/i111.png",
  },
  {
    id: "i112",
    name: "翠晶の指輪",
    description: "緑の光を宿す翠晶を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "A",
    asset: "/items/i112.png",
  },
  {
    id: "i113",
    name: "紅晶の指輪",
    description: "深紅に輝く紅晶を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "A",
    asset: "/items/i113.png",
  },
  {
    id: "i114",
    name: "月銀の指輪",
    description: "月光を帯びる月銀を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "A",
    asset: "/items/i114.png",
  },
  {
    id: "i115",
    name: "蒼玉の指輪",
    description: "魔力を通す蒼玉を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "A",
    asset: "/items/i115.png",
  },
  {
    id: "i116",
    name: "星鉄の指輪",
    description: "隕石から採れた星鉄を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "S",
    asset: "/items/i116.png",
  },
  {
    id: "i117",
    name: "竜鱗鋼の指輪",
    description: "竜鱗を練り込んだ竜鱗鋼を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "S",
    asset: "/items/i117.png",
  },
  {
    id: "i118",
    name: "精霊銀の指輪",
    description: "精霊の加護を宿す精霊銀を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "S",
    asset: "/items/i118.png",
  },
  {
    id: "i119",
    name: "黎明晶の指輪",
    description: "朝焼けを閉じ込めた黎明晶を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "S",
    asset: "/items/i119.png",
  },
  {
    id: "i120",
    name: "永霜晶の指輪",
    description: "溶けない氷の結晶である永霜晶を主材に仕立てた指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "S",
    asset: "/items/i120.png",
  },
  {
    id: "i121",
    name: "創世金の指輪",
    description: "神話の素材「創世金」を核にした指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "SS",
    asset: "/items/i121.png",
  },
  {
    id: "i122",
    name: "天樹の芯の指輪",
    description: "神話の素材「天樹の芯」を核にした指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "SS",
    asset: "/items/i122.png",
  },
  {
    id: "i123",
    name: "時晶の指輪",
    description: "神話の素材「時晶」を核にした指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "SS",
    asset: "/items/i123.png",
  },
  {
    id: "i124",
    name: "星母の涙石の指輪",
    description: "神話の素材「星母の涙石」を核にした指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "SS",
    asset: "/items/i124.png",
  },
  {
    id: "i125",
    name: "不死鳥の羽の指輪",
    description: "神話の素材「不死鳥の羽」を核にした指輪。\n持つと力がみなぎってくる",
    type: "アーティファクト",
    slot: "指輪",
    rarity: "SS",
    asset: "/items/i125.png",
  },
  {
    id: "i126",
    name: "樫の腕輪",
    description: "丈夫な木を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "C",
    asset: "/items/i126.png",
  },
  {
    id: "i127",
    name: "石の腕輪",
    description: "磨き上げた石を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "C",
    asset: "/items/i127.png",
  },
  {
    id: "i128",
    name: "銅の腕輪",
    description: "赤褐色の銅を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "C",
    asset: "/items/i128.png",
  },
  {
    id: "i129",
    name: "青銅の腕輪",
    description: "銅と錫を合わせた青銅を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "C",
    asset: "/items/i129.png",
  },
  {
    id: "i130",
    name: "鉄の腕輪",
    description: "堅実な鉄を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "C",
    asset: "/items/i130.png",
  },
  {
    id: "i131",
    name: "鋼の腕輪",
    description: "よく鍛えた鋼を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "B",
    asset: "/items/i131.png",
  },
  {
    id: "i132",
    name: "銀の腕輪",
    description: "銀を主体とする合金を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "B",
    asset: "/items/i132.png",
  },
  {
    id: "i133",
    name: "黒曜石の腕輪",
    description: "黒く艶やかな黒曜石を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "B",
    asset: "/items/i133.png",
  },
  {
    id: "i134",
    name: "琥珀の腕輪",
    description: "魔力で硬化させた琥珀を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "B",
    asset: "/items/i134.png",
  },
  {
    id: "i135",
    name: "金の腕輪",
    description: "金と他の金属を混ぜた合金を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "B",
    asset: "/items/i135.png",
  },
  {
    id: "i136",
    name: "ミスリルの腕輪",
    description: "軽く青銀色に輝くミスリルを主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "A",
    asset: "/items/i136.png",
  },
  {
    id: "i137",
    name: "翠晶の腕輪",
    description: "緑の光を宿す翠晶を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "A",
    asset: "/items/i137.png",
  },
  {
    id: "i138",
    name: "紅晶の腕輪",
    description: "深紅に輝く紅晶を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "A",
    asset: "/items/i138.png",
  },
  {
    id: "i139",
    name: "月銀の腕輪",
    description: "月光を帯びる月銀を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "A",
    asset: "/items/i139.png",
  },
  {
    id: "i140",
    name: "蒼玉の腕輪",
    description: "魔力を通す蒼玉を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "A",
    asset: "/items/i140.png",
  },
  {
    id: "i141",
    name: "星鉄の腕輪",
    description: "隕石から採れた星鉄を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "S",
    asset: "/items/i141.png",
  },
  {
    id: "i142",
    name: "竜鱗鋼の腕輪",
    description: "竜鱗を練り込んだ竜鱗鋼を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "S",
    asset: "/items/i142.png",
  },
  {
    id: "i143",
    name: "精霊銀の腕輪",
    description: "精霊の加護を宿す精霊銀を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "S",
    asset: "/items/i143.png",
  },
  {
    id: "i144",
    name: "黎明晶の腕輪",
    description: "朝焼けを閉じ込めた黎明晶を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "S",
    asset: "/items/i144.png",
  },
  {
    id: "i145",
    name: "永霜晶の腕輪",
    description: "溶けない氷の結晶である永霜晶を主材に仕立てた腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "S",
    asset: "/items/i145.png",
  },
  {
    id: "i146",
    name: "創世金の腕輪",
    description: "神話の素材「創世金」を核にした腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "SS",
    asset: "/items/i146.png",
  },
  {
    id: "i147",
    name: "天樹の芯の腕輪",
    description: "神話の素材「天樹の芯」を核にした腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "SS",
    asset: "/items/i147.png",
  },
  {
    id: "i148",
    name: "時晶の腕輪",
    description: "神話の素材「時晶」を核にした腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "SS",
    asset: "/items/i148.png",
  },
  {
    id: "i149",
    name: "星母の涙石の腕輪",
    description: "神話の素材「星母の涙石」を核にした腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "SS",
    asset: "/items/i149.png",
  },
  {
    id: "i150",
    name: "不死鳥の羽の腕輪",
    description: "神話の素材「不死鳥の羽」を核にした腕輪。\n不思議な力に守られる安心感",
    type: "アーティファクト",
    slot: "腕輪",
    rarity: "SS",
    asset: "/items/i150.png",
  },
  {
    id: "i151",
    name: "桜木の首飾り",
    description: "丈夫な木を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "C",
    asset: "/items/i151.png",
  },
  {
    id: "i152",
    name: "石の首飾り",
    description: "磨き上げた石を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "C",
    asset: "/items/i152.png",
  },
  {
    id: "i153",
    name: "銅の首飾り",
    description: "赤褐色の銅を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "C",
    asset: "/items/i153.png",
  },
  {
    id: "i154",
    name: "青銅の首飾り",
    description: "銅と錫を合わせた青銅を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "C",
    asset: "/items/i154.png",
  },
  {
    id: "i155",
    name: "鉄の首飾り",
    description: "堅実な鉄を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "C",
    asset: "/items/i155.png",
  },
  {
    id: "i156",
    name: "鋼の首飾り",
    description: "よく鍛えた鋼を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "B",
    asset: "/items/i156.png",
  },
  {
    id: "i157",
    name: "銀の首飾り",
    description: "銀を主体とする合金を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "B",
    asset: "/items/i157.png",
  },
  {
    id: "i158",
    name: "黒曜石の首飾り",
    description: "黒く艶やかな黒曜石を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "B",
    asset: "/items/i158.png",
  },
  {
    id: "i159",
    name: "琥珀の首飾り",
    description: "魔力で硬化させた琥珀を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "B",
    asset: "/items/i159.png",
  },
  {
    id: "i160",
    name: "金の首飾り",
    description: "金と他の金属を混ぜた合金を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "B",
    asset: "/items/i160.png",
  },
  {
    id: "i161",
    name: "ミスリルの首飾り",
    description: "軽く青銀色に輝くミスリルを主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "A",
    asset: "/items/i161.png",
  },
  {
    id: "i162",
    name: "翠晶の首飾り",
    description: "緑の光を宿す翠晶を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "A",
    asset: "/items/i162.png",
  },
  {
    id: "i163",
    name: "紅晶の首飾り",
    description: "深紅に輝く紅晶を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "A",
    asset: "/items/i163.png",
  },
  {
    id: "i164",
    name: "月銀の首飾り",
    description: "月光を帯びる月銀を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "A",
    asset: "/items/i164.png",
  },
  {
    id: "i165",
    name: "蒼玉の首飾り",
    description: "魔力を通す蒼玉を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "A",
    asset: "/items/i165.png",
  },
  {
    id: "i166",
    name: "星鉄の首飾り",
    description: "隕石から採れた星鉄を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "S",
    asset: "/items/i166.png",
  },
  {
    id: "i167",
    name: "竜鱗鋼の首飾り",
    description: "竜鱗を練り込んだ竜鱗鋼を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "S",
    asset: "/items/i167.png",
  },
  {
    id: "i168",
    name: "精霊銀の首飾り",
    description: "精霊の加護を宿す精霊銀を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "S",
    asset: "/items/i168.png",
  },
  {
    id: "i169",
    name: "黎明晶の首飾り",
    description: "朝焼けを閉じ込めた黎明晶を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "S",
    asset: "/items/i169.png",
  },
  {
    id: "i170",
    name: "永霜晶の首飾り",
    description: "溶けない氷の結晶である永霜晶を主材に仕立てた首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "S",
    asset: "/items/i170.png",
  },
  {
    id: "i171",
    name: "創世金の首飾り",
    description: "神話の素材「創世金」を核にした首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "SS",
    asset: "/items/i171.png",
  },
  {
    id: "i172",
    name: "天樹の芯の首飾り",
    description: "神話の素材「天樹の芯」を核にした首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "SS",
    asset: "/items/i172.png",
  },
  {
    id: "i173",
    name: "時晶の首飾り",
    description: "神話の素材「時晶」を核にした首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "SS",
    asset: "/items/i173.png",
  },
  {
    id: "i174",
    name: "星母の涙石の首飾り",
    description: "神話の素材「星母の涙石」を核にした首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "SS",
    asset: "/items/i174.png",
  },
  {
    id: "i175",
    name: "不死鳥の羽の首飾り",
    description: "神話の素材「不死鳥の羽」を核にした首飾り。\n精神力が高まる気がする",
    type: "アーティファクト",
    slot: "首飾り",
    rarity: "SS",
    asset: "/items/i175.png",
  },
  {
    id: "i176",
    name: "白樺の耳飾り",
    description: "丈夫な木を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "C",
    asset: "/items/i176.png",
  },
  {
    id: "i177",
    name: "石の耳飾り",
    description: "磨き上げた石を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "C",
    asset: "/items/i177.png",
  },
  {
    id: "i178",
    name: "銅の耳飾り",
    description: "赤褐色の銅を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "C",
    asset: "/items/i178.png",
  },
  {
    id: "i179",
    name: "青銅の耳飾り",
    description: "銅と錫を合わせた青銅を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "C",
    asset: "/items/i179.png",
  },
  {
    id: "i180",
    name: "鉄の耳飾り",
    description: "堅実な鉄を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "C",
    asset: "/items/i180.png",
  },
  {
    id: "i181",
    name: "鋼の耳飾り",
    description: "よく鍛えた鋼を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "B",
    asset: "/items/i181.png",
  },
  {
    id: "i182",
    name: "銀の耳飾り",
    description: "銀を主体とする合金を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "B",
    asset: "/items/i182.png",
  },
  {
    id: "i183",
    name: "黒曜石の耳飾り",
    description: "黒く艶やかな黒曜石を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "B",
    asset: "/items/i183.png",
  },
  {
    id: "i184",
    name: "琥珀の耳飾り",
    description: "魔力で硬化させた琥珀を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "B",
    asset: "/items/i184.png",
  },
  {
    id: "i185",
    name: "金の耳飾り",
    description: "金と他の金属を混ぜた合金を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "B",
    asset: "/items/i185.png",
  },
  {
    id: "i186",
    name: "ミスリルの耳飾り",
    description: "軽く青銀色に輝くミスリルを主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "A",
    asset: "/items/i186.png",
  },
  {
    id: "i187",
    name: "翠晶の耳飾り",
    description: "緑の光を宿す翠晶を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "A",
    asset: "/items/i187.png",
  },
  {
    id: "i188",
    name: "紅晶の耳飾り",
    description: "深紅に輝く紅晶を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "A",
    asset: "/items/i188.png",
  },
  {
    id: "i189",
    name: "月銀の耳飾り",
    description: "月光を帯びる月銀を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "A",
    asset: "/items/i189.png",
  },
  {
    id: "i190",
    name: "蒼玉の耳飾り",
    description: "魔力を通す蒼玉を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "A",
    asset: "/items/i190.png",
  },
  {
    id: "i191",
    name: "星鉄の耳飾り",
    description: "隕石から採れた星鉄を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "S",
    asset: "/items/i191.png",
  },
  {
    id: "i192",
    name: "竜鱗鋼の耳飾り",
    description: "竜鱗を練り込んだ竜鱗鋼を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "S",
    asset: "/items/i192.png",
  },
  {
    id: "i193",
    name: "精霊銀の耳飾り",
    description: "精霊の加護を宿す精霊銀を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "S",
    asset: "/items/i193.png",
  },
  {
    id: "i194",
    name: "黎明晶の耳飾り",
    description: "朝焼けを閉じ込めた黎明晶を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "S",
    asset: "/items/i194.png",
  },
  {
    id: "i195",
    name: "永霜晶の耳飾り",
    description: "溶けない氷の結晶である永霜晶を主材に仕立てた耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "S",
    asset: "/items/i195.png",
  },
  {
    id: "i196",
    name: "創世金の耳飾り",
    description: "神話の素材「創世金」を核にした耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "SS",
    asset: "/items/i196.png",
  },
  {
    id: "i197",
    name: "天樹の芯の耳飾り",
    description: "神話の素材「天樹の芯」を核にした耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "SS",
    asset: "/items/i197.png",
  },
  {
    id: "i198",
    name: "時晶の耳飾り",
    description: "神話の素材「時晶」を核にした耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "SS",
    asset: "/items/i198.png",
  },
  {
    id: "i199",
    name: "星母の涙石の耳飾り",
    description: "神話の素材「星母の涙石」を核にした耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "SS",
    asset: "/items/i199.png",
  },
  {
    id: "i200",
    name: "不死鳥の羽の耳飾り",
    description: "神話の素材「不死鳥の羽」を核にした耳飾り。\n稀に奇跡をおこすかもしれない",
    type: "アーティファクト",
    slot: "耳飾り",
    rarity: "SS",
    asset: "/items/i200.png",
  },
  {
    id: "i201",
    name: "楓のブローチ",
    description: "丈夫な木を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "C",
    asset: "/items/i201.png",
  },
  {
    id: "i202",
    name: "石のブローチ",
    description: "磨き上げた石を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "C",
    asset: "/items/i202.png",
  },
  {
    id: "i203",
    name: "銅のブローチ",
    description: "赤褐色の銅を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "C",
    asset: "/items/i203.png",
  },
  {
    id: "i204",
    name: "青銅のブローチ",
    description: "銅と錫を合わせた青銅を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "C",
    asset: "/items/i204.png",
  },
  {
    id: "i205",
    name: "鉄のブローチ",
    description: "堅実な鉄を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "C",
    asset: "/items/i205.png",
  },
  {
    id: "i206",
    name: "鋼のブローチ",
    description: "よく鍛えた鋼を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "B",
    asset: "/items/i206.png",
  },
  {
    id: "i207",
    name: "銀のブローチ",
    description: "銀を主体とする合金を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "B",
    asset: "/items/i207.png",
  },
  {
    id: "i208",
    name: "黒曜石のブローチ",
    description: "黒く艶やかな黒曜石を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "B",
    asset: "/items/i208.png",
  },
  {
    id: "i209",
    name: "琥珀のブローチ",
    description: "魔力で硬化させた琥珀を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "B",
    asset: "/items/i209.png",
  },
  {
    id: "i210",
    name: "金のブローチ",
    description: "金と他の金属を混ぜた合金を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "B",
    asset: "/items/i210.png",
  },
  {
    id: "i211",
    name: "ミスリルのブローチ",
    description: "軽く青銀色に輝くミスリルを主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "A",
    asset: "/items/i211.png",
  },
  {
    id: "i212",
    name: "翠晶のブローチ",
    description: "緑の光を宿す翠晶を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "A",
    asset: "/items/i212.png",
  },
  {
    id: "i213",
    name: "紅晶のブローチ",
    description: "深紅に輝く紅晶を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "A",
    asset: "/items/i213.png",
  },
  {
    id: "i214",
    name: "月銀のブローチ",
    description: "月光を帯びる月銀を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "A",
    asset: "/items/i214.png",
  },
  {
    id: "i215",
    name: "蒼玉のブローチ",
    description: "魔力を通す蒼玉を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "A",
    asset: "/items/i215.png",
  },
  {
    id: "i216",
    name: "星鉄のブローチ",
    description: "隕石から採れた星鉄を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "S",
    asset: "/items/i216.png",
  },
  {
    id: "i217",
    name: "竜鱗鋼のブローチ",
    description: "竜鱗を練り込んだ竜鱗鋼を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "S",
    asset: "/items/i217.png",
  },
  {
    id: "i218",
    name: "精霊銀のブローチ",
    description: "精霊の加護を宿す精霊銀を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "S",
    asset: "/items/i218.png",
  },
  {
    id: "i219",
    name: "黎明晶のブローチ",
    description: "朝焼けを閉じ込めた黎明晶を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "S",
    asset: "/items/i219.png",
  },
  {
    id: "i220",
    name: "永霜晶のブローチ",
    description: "溶けない氷の結晶である永霜晶を主材に仕立てたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "S",
    asset: "/items/i220.png",
  },
  {
    id: "i221",
    name: "創世金のブローチ",
    description: "神話の素材「創世金」を核にしたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "SS",
    asset: "/items/i221.png",
  },
  {
    id: "i222",
    name: "天樹の芯のブローチ",
    description: "神話の素材「天樹の芯」を核にしたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "SS",
    asset: "/items/i222.png",
  },
  {
    id: "i223",
    name: "時晶のブローチ",
    description: "神話の素材「時晶」を核にしたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "SS",
    asset: "/items/i223.png",
  },
  {
    id: "i224",
    name: "星母の涙石のブローチ",
    description: "神話の素材「星母の涙石」を核にしたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "SS",
    asset: "/items/i224.png",
  },
  {
    id: "i225",
    name: "不死鳥の羽のブローチ",
    description: "神話の素材「不死鳥の羽」を核にしたブローチ。\nいざというとき頑張れそう",
    type: "アーティファクト",
    slot: "ブローチ",
    rarity: "SS",
    asset: "/items/i225.png",
  },
  {
    id: "i226",
    name: "杉の帯留め",
    description: "丈夫な木を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "C",
    asset: "/items/i226.png",
  },
  {
    id: "i227",
    name: "石の帯留め",
    description: "磨き上げた石を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "C",
    asset: "/items/i227.png",
  },
  {
    id: "i228",
    name: "銅の帯留め",
    description: "赤褐色の銅を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "C",
    asset: "/items/i228.png",
  },
  {
    id: "i229",
    name: "青銅の帯留め",
    description: "銅と錫を合わせた青銅を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "C",
    asset: "/items/i229.png",
  },
  {
    id: "i230",
    name: "鉄の帯留め",
    description: "堅実な鉄を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "C",
    asset: "/items/i230.png",
  },
  {
    id: "i231",
    name: "鋼の帯留め",
    description: "よく鍛えた鋼を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "B",
    asset: "/items/i231.png",
  },
  {
    id: "i232",
    name: "銀の帯留め",
    description: "銀を主体とする合金を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "B",
    asset: "/items/i232.png",
  },
  {
    id: "i233",
    name: "黒曜石の帯留め",
    description: "黒く艶やかな黒曜石を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "B",
    asset: "/items/i233.png",
  },
  {
    id: "i234",
    name: "琥珀の帯留め",
    description: "魔力で硬化させた琥珀を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "B",
    asset: "/items/i234.png",
  },
  {
    id: "i235",
    name: "金の帯留め",
    description: "金と他の金属を混ぜた合金を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "B",
    asset: "/items/i235.png",
  },
  {
    id: "i236",
    name: "ミスリルの帯留め",
    description: "軽く青銀色に輝くミスリルを主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "A",
    asset: "/items/i236.png",
  },
  {
    id: "i237",
    name: "翠晶の帯留め",
    description: "緑の光を宿す翠晶を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "A",
    asset: "/items/i237.png",
  },
  {
    id: "i238",
    name: "紅晶の帯留め",
    description: "深紅に輝く紅晶を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "A",
    asset: "/items/i238.png",
  },
  {
    id: "i239",
    name: "月銀の帯留め",
    description: "月光を帯びる月銀を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "A",
    asset: "/items/i239.png",
  },
  {
    id: "i240",
    name: "蒼玉の帯留め",
    description: "魔力を通す蒼玉を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "A",
    asset: "/items/i240.png",
  },
  {
    id: "i241",
    name: "星鉄の帯留め",
    description: "隕石から採れた星鉄を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "S",
    asset: "/items/i241.png",
  },
  {
    id: "i242",
    name: "竜鱗鋼の帯留め",
    description: "竜鱗を練り込んだ竜鱗鋼を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "S",
    asset: "/items/i242.png",
  },
  {
    id: "i243",
    name: "精霊銀の帯留め",
    description: "精霊の加護を宿す精霊銀を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "S",
    asset: "/items/i243.png",
  },
  {
    id: "i244",
    name: "黎明晶の帯留め",
    description: "朝焼けを閉じ込めた黎明晶を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "S",
    asset: "/items/i244.png",
  },
  {
    id: "i245",
    name: "永霜晶の帯留め",
    description: "溶けない氷の結晶である永霜晶を主材に仕立てた帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "S",
    asset: "/items/i245.png",
  },
  {
    id: "i246",
    name: "創世金の帯留め",
    description: "神話の素材「創世金」を核にした帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "SS",
    asset: "/items/i246.png",
  },
  {
    id: "i247",
    name: "天樹の芯の帯留め",
    description: "神話の素材「天樹の芯」を核にした帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "SS",
    asset: "/items/i247.png",
  },
  {
    id: "i248",
    name: "時晶の帯留め",
    description: "神話の素材「時晶」を核にした帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "SS",
    asset: "/items/i248.png",
  },
  {
    id: "i249",
    name: "星母の涙石の帯留め",
    description: "神話の素材「星母の涙石」を核にした帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "SS",
    asset: "/items/i249.png",
  },
  {
    id: "i250",
    name: "不死鳥の羽の帯留め",
    description: "神話の素材「不死鳥の羽」を核にした帯留め。\n身に着けると気持ちが引き締まる",
    type: "アーティファクト",
    slot: "帯留め",
    rarity: "SS",
    asset: "/items/i250.png",
  },
];

export function getItemBaseInfo(id: string): ItemBaseInfo | undefined {
  return ITEM_BASE_INFO.find((i) => i.id === id);
}
